### ISSUE TITLE
Proper handling of runtime-exceptions in jitter and ping

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#115]
**Describe the bug**
When the jitter or ping operation is performed on IP addresses which are not valid, it leads to flooding of logs in the terminal. This needs to be avoided and rather a single line indicating teh kind of failure should be shown.

**Comment by aquibbaig** [comment]
**Handling of runtime exceptions** in a broader sense requires to know what all exceptions and errors can arise in the runtime of a process, say: jitter analysis. @Harkishen-Singh Please modify #115 with respect to this. Handling exceptions should be aimed at handling any mishaps that break the process in any way(for example: A faulty URI and how we handle that when one occurs, do we stop the current goroutine, or the entire thread). That was an implementation example, not a real case scenario. The issue mentioned here deals with more of logging/debugging rather than handling anything. So, we have to either rename the issue or extend it. Thoughts?

**Comment by muskankhedia** [comment]
In case there is an invalid URL or when the CLI returns an error, we can create a separate module to handle all the errors, handling all the different conditions possible. Like two of the possible conditions can be, one is invalid URL and the other one checking the internet connection and accordingly, the log can be maintained with proper details and the issue. I think it's better to open a separate issue for this. @aquibbaig @Harkishen-Singh what do you think?

**Comment by Harkishen-Singh** [comment]
@muskankhedia yeah, that would be better. And accordingly, the user can be alerted by the alerting system _(once its ready to)_

**Comment by Harkishen-Singh** [comment]
With the merge of #288, this is covered. Hence, closing.
