### ISSUE TITLE
save the response length and fetch when required

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes#23]
The response returned by the response module is subject to disappear when the user closes the application and restart this.

 Before the user closes the application we need to save this data somewhere either as a DB entry/JSON dump.

This will help us to have an already stored length field  for the routes which can be referred from when calculating response changes in the future

**Comment by aquibbaig** [comment]
#24 depends on this!

**Comment by aquibbaig** [comment]
I'm assigning myself for this for now!

**Comment by Harkishen-Singh** [comment]
@aquibbaig @dikshantbrahma @ganeshpatro321  please have a look on this. This remains an important feature.

**Comment by Harkishen-Singh** [comment]
With the introduction of batch-writes, the data that is left over is now equal to the ones gathered within the buffer seconds only. This is crucial but seems no way to fix right now. Even other monitoring tools lose their data in this period. Disk write is not an option since we want to lessen the IO. Hence, only in-memory remains an option, which again means that on closing, data loss will occur. Hence, closing for now. If someone gets an idea, free feel to open this.
