### ISSUE TITLE
Implement Modules UI page in v1.1

### ISSUE THREAD

**Issue by ganeshpatro321** [zairza-cetb/bench-routes#244]
Test and Monitoring UI pages such as Ping, jitter, FloodPing have to be implemented in the v1.1.

- [x] Ping
- [ ] FloodPing
- [ ] Jitter
- [ ] Req-Res

**Comment by muskankhedia** [comment]
@ganeshpatro321 I am currently working on setting up the ping module in the UI for now. Will get it completed in 2-3 days.
We have created a new design for that. It looks a bit untidy for now because of the work-frame. [Link](https://www.figma.com/file/svTa6jAUUeMmm4MFN3vXgo/Bench-Routes-1.1?node-id=0%3A1)
Please have a look and suggest changes, if any.

**Comment by ganeshpatro321** [comment]
@muskankhedia Looks good. I was just starting to work on the ping page. Anyways, would you like me to setup the socket connection as it was in v1.0?

**Comment by muskankhedia** [comment]
@ganeshpatro321 As per the current discussion, I used API for retrieving the data from the backend. 
Further, I think @Harkishen-Singh can guide us better.

**Comment by Harkishen-Singh** [comment]
This approach has been changed and the #251 solves this!

**Comment by Harkishen-Singh** [comment]
I think this is addressed.
